### ISSUE TITLE
attributes not removed / caching problem?

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1144]
MISP v 2.4.44

How to reproduce:
- Create an Event, with one attribute
- Search for the attribute, you will have a result
- Go back to the Event, remove the attribute. Notice that the event does not contain the attribute anymore
- Search for the same attribute, you will have a result
- Edit the attribute: the attribute edit window will be shown and you can edit the attribute. Look at the sourcecode of this page, you will see the associated eventid
- try to delete that attribute, you will get the error "invalid attribute".

This might be related to some server-side caching somewhere. It is not client side. (tested with another computer/browser to search for the removed attribute )

**Comment by iglocska** [comment]
Fixed this for now, we'll revisit the optional hard delete and showing it to the creator at a later date. Extend my thanks to JF please!

**Comment by cvandeplas** [comment]
The fact that removed data is not shown to the creator (org) has the consequence of potential information leakage. If an analyst adds something he shouldn't have added, removes it and doesn't see that it's still there he will cause an incident of information leakage. 

I understood that the admin can still see and undelete the data, is it so complex to add the same feature for the user part of the same org?

**Comment by iglocska** [comment]
Definitely not and will implement it asap. The plan is to make it visible
to the creator org too and allow him/her to undelete.

The hard delete on the other hand is a bit trickier.

**Comment by cvandeplas** [comment]
About the hard delete: I think most often this happens before the event has been (re)published. So the sync propagation should not cause too much issues as the 'to be deleted information' was not yet propagated.

**Comment by iglocska** [comment]
Indeed, it shouldn't cause issues, but it's more of a nice to have feature
that is to be implemented. We can put it in the queue, but it's a bit lower
in prio. Deleting the event if something absolutely critically dangerous
ends up in a yet unpublished event will hard-delete it as it is already.

**Comment by iglocska** [comment]
Added the option for users to see and undelete their own org's deleted attributes.

**Comment by iglocska** [comment]
Added it after all, feature creep FTW.
