### ISSUE TITLE
MISP Partner sync events error

### ISSUE THREAD

**Issue by luna7391** [MISP/MISP#3898]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Question?
| OS version (server)       | Redhat 7.5
| OS version (client)       | 
| PHP version               | 7.1.8
| MISP version / git hash   | 2.4.97
| Browser                   | 

### Expected behavior
I've built a MISP instance following the INSTALL.rhel7 document. The instance has been configured to sync with an external partner, the server connection test reports:
Local version: 2.4.97
Remote version: 2.4.97
Status: OK
Compatiblity: Compatible
POST test: Received sent package

After a Pull request 86,939 events have been pulled down, the sync task ran without issue up until this point but now the error below is being experienced. Test events have successfully been pushed to the partners MISP instance. Expected behaviour is that the sync job should pull all remaining events from the partner server.

### Actual behavior
Although 86,939 events have successfully been pulled down, the pull request is now reporting the error below when running “cd /var/www/MISP/app/Console && ./cake Server pull 10 2 full”. Each time this command is run a new event is pulled down but the process then stops.

### Steps to reproduce the behavior
Running cd /var/www/MISP/app/Console && ./cake Server pull 10 2 full

### Logs, screenshots, configuration dump, ...
Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Object' for column 'referenced_type' at row 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(ObjectReference), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/ObjectReference.php(251): Model->save(Array)
#6 /var/www/MISP/app/Model/Event.php(3224): ObjectReference->captureReference(Array, '86938', Array, Object(Log))
#7 /var/www/MISP/app/Model/Server.php(1897): Event->_add(Array, true, Array, '1', '2', true, '201')
#8 /var/www/MISP/app/Model/Server.php(1928): Server->__checkIfPulledEventExistsAndAddOrUpdate(Array, '5aaa3126-0b38-4...', Array, Array, Object(Event), Array, Array, '201')
#9 /var/www/MISP/app/Model/Server.php(2034): Server->__pullEvent('5aaa3126-0b38-4...', Array, Array, Object(Event), Array, Array, '201')
#10 /var/www/MISP/app/Console/Command/ServerShell.php(40): Server->pull(Array, '2', 'full', Array, '201')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('pull', Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#15 {main}

**Comment by iglocska** [comment]
This should be fixed on the latest commit, thanks to @cvandeplas

**Comment by luna7391** [comment]
Hi @iglocska, I'm completely new to this so appologies for such a basic question. What do I need to run?

**Comment by adulau** [comment]
Just `git pull origin 2.4` in your MISP directory would do the job ;-)

**Comment by luna7391** [comment]
Thanks @adulau, I've run the command, in the GUI I now get:

Currently installed version… v2.4.97 (af715c7b755882968b350a0f7584388dbdcfbbca)
Latest available version… v2.4.97 (af715c7b755882968b350a0f7584388dbdcfbbca)
Status… OK
Current branch… You are not on a branch, Update MISP will fail 

git status displays:
 HEAD detached from v2.4.95
 Changes not staged for commit:
   (use "git add <file>..." to update what will be committed)
   (use "git checkout -- <file>..." to discard changes in working directory)

       modified:   PyMISP (new commits)
       modified:   app/composer.json
       modified:   app/files/misp-galaxy (new commits)
       modified:   app/files/misp-objects (new commits)
       modified:   app/files/taxonomies (new commits)
       modified:   app/files/warninglists (new commits)

 Untracked files:
   (use "git add <file>..." to include in what will be committed)

       app/Config/config.27092018.php
       app/Config_working_20180927/
       app/Config_working_updated_config_20180927/
       app/webroot/phpinfo.php
no changes added to commit (use "git add" and/or "git commit -a")

[root@mispext1nec /var/www/MISP] git branch
* (detached from v2.4.95)
  2.4

Being new to this I don't want to risk botching things up so would value advise on the steps to get to the correct branch. Is it as simple of git checkout 2.4?  On a normal day to day support basis would there be any need to create/switch branches? Thanks.

**Comment by luna7391** [comment]
Thanks for the previous responses.

After switching to the 2.4 branch and running git pull origin 2.4, the pull command is pulling more events than it was prior to the update but still fails. However I notice when checking the events that the task always fails on a **CIRCL** event that has a **Published** status of **No**, other **CIRCL** events with published status of **Yes** are pulled without issue. Anyone else experienced this issue?

Also since the last commit I get the following:

Writeable Files
/var/www/MISP/app/Config/config.php…OK
**/var/www/MISP/.git/ORIG_HEAD…File is not writeable**

I've amended the permissions (to apache) but this has not resolved the issue. Again any assistance would be appreciated.

**Comment by luna7391** [comment]
Hi, just following-up on the two issues above (with CIRCL events and ORIG_HEAD), has anyone else experienced these and if so how did you resolve them (I've tried changing permissions on the latter)? Thanks.
