### ISSUE TITLE
SMTP settings?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#4422]
While searching for details about SMTP settings, I found the case #418.
What about having a SMTP config in MISP itself? To prevent the installation of a Postfix instance and use an existing relay (often already available in corporate environments).

**Comment by iwitz** [comment]
To use an existing SMTP server I did the following :

1. Install sendmail
2. Configure it to use your SMTP server (change the SMART_HOST value in /etc/mail/sendmail.mc)
3. systemctl enable --now sendmail

Then by default the php.ini file should have the correct sendmail location (depends of your distribution), in which case email sending should now work. You don't have to install an SMTP server on your MISP box.

**Comment by MarkDevelo** [comment]
Hi , i have a MISP server and a Postfix server in differents IPs in the same LAN, but i can't find a way to set my MISP server to use my Postfix server to send the email notifications. Can anyone help me please ? I access my servers through IP address, i use Ubuntu 16.04, MISP version 2.4.120... Thanks

**Comment by RichieB2B** [comment]
You can set the SMTP server in the php.ini
It is not MISP specific.

**Comment by MarkDevelo** [comment]
Hi @RichieB2B , i've read about the sendmail_path ="/usr/sbin/sendmail -t -i" in the php.ini but still doesn't work. What else can i do ? I've tried to change the famous SMART_HOST in the sendmail.mc but apparently it doesn't work with IP address. Is there a painless way to make the MISP to send emails ? I just need my MISP in the 10.15.12.13 to send an email using my 10.15.12.18 email server. Thanks for your time.

**Comment by RichieB2B** [comment]
Try this in php.ini:
`SMTP = 10.15.12.18`

**Comment by MarkDevelo** [comment]
Hi @RichieB2B , I've tried that as well, but apparently that's for win32 i think, nevertheless i've already tried that line and also commenting that line when using the sendmail_path ="/usr/sbin/sendmail -t -i". Thanks for your time.

**Comment by coolacid** [comment]
You can set SMTP settings in the email.php config file: https://github.com/MISP/MISP/blob/2.4/app/Config/email.php

I ended up changing each of the default/smtp/fast to match what my requirements were and was able to send emails without issues. 

This should probably be documented, and maybe even cleaned up as I'm not sure which of the vars are actually user/required.

**Comment by MarkDevelo** [comment]
Hi @coolacid , @RichieB2B thanks for your help, but was a problem with my DNS, i had to add my email server IP and name to /etc/hosts file. Thanks once again for your time.

**Comment by teward** [comment]
I'm just going to give an update what I did to make this work on the system.

We run MISP on Ubuntu systems, so we did a clean Postfix install with a smarthost setup that points to our email system that actually can send out the door.  This way, when MISP or the PHP function pull in 'mail' commands and use sendmail, it goes to Postfix via localhost, and then to the actual proper smarthost.

It'd be nice to configure the Email SMTP functionality *within* MISP's settings, however, in a pinch you can either do a Postfix style smarthost setup or change SMTP settings in the PHP itself.

**Comment by pietrogu** [comment]
Hi,

could someone document how to properly set emailing for misp?

thanks,
Pietro

**Comment by KTanAug21** [comment]
Overview:
1. Configure email.config
2. Make sure no MISP settings is prohibiting email sending
____________________________________________________________________________________________
### 1. Configure email.config
There should be an email config file for MISP:
.../MISP/app/Config/email.php

You can add your smtp/gmail/other provider configuration there.

### 2. Make sure no MISP settings is prohibiting email sending
1. MISP.disable_emailing = false

Afterwards, if you haven't configured any GnuPG keys for your users, please make sure that encryption settings wont prohibit your sending: _( Below settings are for testing purposes only, so that you can test if your config is working. Enable the values again once you have proper encryption or done testing your config )_
3. GnuPG.onlyencrypted = false 
4. GnuPG.bodyonlyencrypted = false

**Comment by Phatkone** [comment]
I had to set the relayhost field in /etc/postfix/main.cf, I did that along with the above changes in email.php and it now works. 
Hope that is of help to people.

**Comment by HachimanSec** [comment]
Hi everyone, 
I came across this issue based on my current problems to setup email for the latest MISP version. 
As mentioned I tried to configure email.php - my SMTP server uses tls and PLAIN AUTH. 

However all I get is: 
```
**[SocketException] SMTP Error: 535 5.7.8 Error: authentication failed: Invalid authentication mechanism**
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/SmtpTransport.php(186): SmtpTransport->_smtpSend()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/SmtpTransport.php(87): SmtpTransport->_auth()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/CakeEmail.php(1183): SmtpTransport->send()
#3 /var/www/MISP/app/Lib/Tools/SendEmail.php(156): CakeEmail->send()
#4 /var/www/MISP/app/Lib/Tools/SendEmail.php(558): CakeEmailExtended->send()
#5 /var/www/MISP/app/Model/User.php(891): SendEmail->sendToUser()
#6 /var/www/MISP/app/Controller/UsersController.php(1684): User->sendEmail()
#7 [internal function]: UsersController->admin_email()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#12 {main}
```

Does anyone know how to fix this? I am totally lost. I also tried various options like: 
 ```
       'auth'          => true,
        'authMethod'    => 'PLAIN' 
```

Thanks!
