### ISSUE TITLE
ATT&CK Impact Tactic missing from matrix

### ISSUE THREAD

**Issue by Andy-Dove** [MISP/MISP#4606]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 14.04
| PHP version               | 5.5
| MISP version / git hash   | 2.4.106
| Browser                   | Chrome

### Expected behavior

To be able to add Galaxy entries for the new ATT&CK Impact Tactics, these are included in the galaxy.

### Actual behavior

Tactic missing from matrix.  When trying to add manually screen hangs with a loading icon and the entry is not added.

### Steps to reproduce the behavior
From any event try the following:
Galaxy
Add
Mitre-Attack
All Clusters
Type "DGA" and select the tecnhique that comes up
Add

Screen should go to loading icon and nothing further happens.  Refreshing the screen returns to the previous view without the Galaxy having been added.

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/31212540/57439904-e65e7680-723e-11e9-8998-e3c5a293a89b.png)

**Comment by adulau** [comment]
I tested with 4b48349e23b56ea58796f762a9031dd0b71ab7f9 (latest version of the HEAD) and I can add the cluster. Don't you have any plug-ins such as NoScript or alike?

**Comment by adulau** [comment]
Correction, I can reproduce it when opening and closing the ATT\&CK visualisation matrix before. Indeed, there is a bug.

**Comment by Andy-Dove** [comment]
Thanks for looking at this guys. I can confirm that I don't have NoScript or similar running and that the rest of the matrix is performing as expected.

**Comment by mokaddem** [comment]
Hello!
The bug has been fixed in de186f93ad75d89eeb57fd72867f81c32b728899. Missing entries are delegated to issue #4609.

**Comment by Andy-Dove** [comment]
I pulled this down this morning and the issue appears to be still there. Do I need to be pulling from somewhere other than the main repository?

**Comment by mokaddem** [comment]
From HEAD it should work (also, we just re-tagged MISP 2.4.107). Could you SHIFT-reload and try again?
If it still doesn't work, we might have solved a different bug.

**Comment by Andy-Dove** [comment]
Thanks Sami,

 

I’m pulling down with “git pull origin 2.4”. Still not seeing the impact column in the matrix and still now able to add DGA technique and so on.

 

Kind regards,

 

Andy Dove

 

Intrusion Analyst

Overwatch

CrowdStrike Inc.

www.crowdstrike.com

**Comment by mokaddem** [comment]
In order to have the impact column in the matrix, you will also have to update your galaxies.

**Comment by Andy-Dove** [comment]
Thanks Sammi,

 

All working now.  You guys are the best.

 

Kind regards,

 

Andy Dove

 

Intrusion Analyst

Overwatch

CrowdStrike Inc.

www.crowdstrike.com

**Comment by adulau** [comment]
Great! Thanks for the feedback and reporting.
