### ISSUE TITLE
STIX 1.1.1 Import does not recognise URLs

### ISSUE THREAD

**Issue by dn2020gh** [MISP/MISP#5894]
Hi,

In your Event section, when I import STIX 1.1.1 xml file, it never seems to recognize URLs as indicator/attribute.

See attached xml report from IBM Exchange with 1 URL in it. I tried it with other STIX 1 reports, URLs never recognised

Is there anything I can do in settings/config to enable it recognizing?

Thanks

[xfe-collection_8cdbf707a0776a9b31466a271ee4ecd0.zip](https://github.com/MISP/MISP/files/4613595/xfe-collection_8cdbf707a0776a9b31466a271ee4ecd0.zip)

**Comment by RichieB2B** [comment]
I can confirm this issue with MISP 2.4.125 f659ee58718d82298a96282bd54493715788db11

**Comment by dn2020gh** [comment]
@RichieB2B  thanks...so do we wait for new version on this? I am on 2.4.125 now

As a side note, I am trying to use STIX 1 import at the moment as STIX 2 JSON gives me the following error:

_Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool._

...so cant upload either STIX 1 or 2..started happening on the weekend for no reason.

Here are my module versions, I am assuming they are up to date:
STIX: >1.2.0.6
CyBox: >2.1.0.21
mixbox: 1.0.3
maec: >4.1.0.14
STIX2: >1.2.0
PyMISP: >2.4.120

**Comment by chrisr3d** [comment]
@dn2020gh I am working on fixing this stix1 issue atm, is it possible you also provide a stix 2 json that I could use to find where your issue comes from?

**Comment by dn2020gh** [comment]
> 
> 
> @dn2020gh I am working on fixing this stix1 issue atm, is it possible you also provide a stix 2 json that I could use to find where your issue comes from?

Chris, attached is 2 samples that I tried yesterday. These IBM X-Force Exchange reports.

Everything was fine last week in terms of importing those types of reports in STIX 2 json format

Thanks

[JSON2 samples.zip](https://github.com/MISP/MISP/files/4614887/JSON2.samples.zip)

**Comment by RichieB2B** [comment]
When checking the module version, be sure to look the installed versions, not the minimal required versions you quoted:
```
Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
STIX2 library version…OK
PYMISP library version…OK
```

**Comment by dn2020gh** [comment]
> 
> 
> When checking the module version, be sure to look the installed versions, not the minimal required versions you quoted:
> 
> ```
> Current libraries status…OK
> STIX library version…OK
> CYBOX library version…OK
> MIXBOX library version…OK
> MAEC library version…OK
> STIX2 library version…OK
> PYMISP library version…OK
> ```

Sorry yes, all good from my end on this:

Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
STIX2 library version…OK
PYMISP library version…OK

I have even tried a fresh  2.4.125 install on new VM, still getting the same issue

**Comment by chrisr3d** [comment]
There was an error with the uuid parsing of the URL object, it should be working now after a pull of the latest version, but let me know if anything goes wrong.
(I will also reply to #5886 directly there once it is fixed, thanks for the sample files)

**Comment by RichieB2B** [comment]
Should be fixed with d0e0ec0c0ed69ad34994aa225ac635e2a3ad02cb

**Comment by RichieB2B** [comment]
I can confirm d0e0ec0c0ed69ad34994aa225ac635e2a3ad02cb fixed the URIObject import issue.

It looks like cd0bb3de7a6ead4db10b16a9012eebb609b5a48b  broke something though:
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1446, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1441, in main
    stix_parser.build_misp_event(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 87, in build_misp_event
    self.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1208, in build_misp_dict
    self.parse_ttps(self.event.ttps.ttp)
AttributeError: 'TTPs' object has no attribute 'ttp'
```

After reverting cd0bb3de7a6ead4db10b16a9012eebb609b5a48b all is fine importing the supplied `xfe-collection_8cdbf707a0776a9b31466a271ee4ecd0.xml`

**Comment by adulau** [comment]
Thanks for the tests. @chrisr3d could you have a look? Thanks a lot

**Comment by RichieB2B** [comment]
Ok, got it; this was changed in [ttps.py](https://github.com/STIXProject/python-stix/blob/master/stix/core/ttps.py) with [507f5d65c1912660c562a04827b842e0e8fc37d1](https://github.com/STIXProject/python-stix/commit/507f5d65c1912660c562a04827b842e0e8fc37d1) so MISP now has a dependency for python-stix v1.2.0.9 or greater. I was on v1.2.0.7 before.

This is bound to have impact for [misp2stix.py](https://github.com/MISP/MISP/blob/2.4/app/files/scripts/misp2stix.py) as well.

**Comment by iglocska** [comment]
We should bump the required version then - if there are material changes to STIX 1 it makes sense, we should align with the latest stable either way. I am somewhat surprised that it's still maintained o.O

**Comment by RichieB2B** [comment]
python-stix v1.2.0.9 was released on Thu Apr 16, 2020 so everyone using STIX in MISP will need to update.

**Comment by iglocska** [comment]
Do you reckon it's better to stick to 1.2.0.7? Anything worthwhile that changed that we might miss out on?

**Comment by RichieB2B** [comment]
Not really, I’m just surprised they made a property change like this so late in the game. Perhaps it’s a bug in v1.2.0.9 that they renamed it from `ttps` to `ttp`?

**Comment by RichieB2B** [comment]
Hmmm, looking at [2720066fddf2af17216a25d38099f579cd2f6406](https://github.com/STIXProject/python-stix/commit/2720066fddf2af17216a25d38099f579cd2f6406) it becomes clear they changed the property from stix.EntityList to stix.Entity so the name change makes sense unfortunately. Upgrading to v1.2.0.9 seems like the best way to go.

[misp2stix.py](https://github.com/MISP/MISP/blob/2.4/app/files/scripts/misp2stix.py) does not seem to use the `ttps` property directly but calls `add_ttp()` so should be unaffected.

**Comment by dn2020gh** [comment]
Hi All,

Thanks for the analysis, so how exactly do I update my instance then. I updated through the GUI, restarted but the same issue still occuring, same output in the logs:

_Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 104, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 225, in clean
    valid = self.contained.clean(item)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/properties.py", line 722, in clean
    parsed_obj = parse(dictified, allow_custom=self.allow_custom, interoperability=self.interoperability)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, interoperability, version)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, interoperability=interoperability, **stix_dict)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/v20/sdo.py", line 256, in __init__
    super(Report, self).__init__(*args, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 334, in __init__
    super(_DomainObject, self).__init__(*args, **kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 196, in __init__
    raise MissingPropertiesError(cls, missing_kwargs)
stix2.exceptions.MissingPropertiesError: No values for required properties for Report: (labels, name, object_refs, published).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1578, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1569, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, interoperability, version)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, interoperability=interoperability, **stix_dict)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/v20/bundle.py", line 42, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 199, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/stix2/base.py", line 114, in _check_property
    exc,
  File "<string>", line 3, in raise_from
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': No values for required properties for Report: (labels, name, object_refs, published)._



My  python-stix is on v1.2.0.10

**Comment by RichieB2B** [comment]
Did you update python-stix in your MISP venv? That should fix the error you are seeing.

**Comment by dn2020gh** [comment]
> 
> 
> Did you update python-stix in your MISP venv? That should fix the error you are seeing.

I have updated MISP from the Gui under Diagnostics, is that the correct way?

Or will I need to be pulling this specific branch and if so how do I do it: https://github.com/MISP/MISP/commit/d0e0ec0c0ed69ad34994aa225ac635e2a3ad02cb

**Comment by RichieB2B** [comment]
You need to re-run the python-stix part from the install guide to update it inside the venv.

**Comment by dn2020gh** [comment]
> 
> 
> You need to re-run the python-stix part from the install guide to update it inside the venv.

If you talking about instructions here:

https://www.circl.lu/doc/misp/updating-python/

...yes I have ran all these commands successfully....stix module is at 1.2.0.10 version but still getting the same error.

I think stix module aside, where was the actual fix done? Was it at the d0e0ec0 branch and I am getting that branch when I go through update instructions in here: https://www.circl.lu/doc/misp/updating-python/ ?

**Comment by RichieB2B** [comment]
Now I see you posted stix2 errors this morning. Those are unrelated with fix d0e0ec0c0ed69ad34994aa225ac635e2a3ad02cb which fixes the stix 1.1.1 issue. You really should open a new issue for the stix2 case to avoid this type of confusion.

Please test with the stix 1.1.1 xfe-collection_8cdbf707a0776a9b31466a271ee4ecd0.xml file.

**Comment by dn2020gh** [comment]
All good now with stix 1, sorry for confusion, I have raised a separate issue for stix 2, will track it there.

Thank you to everyone for their help!

**Comment by chrisr3d** [comment]
You are welcome

Thank you @RichieB2B for the clarification, I updated the value of the required version in the diagnostic tool.

I will try to be careful with the versions ;-)
