### ISSUE TITLE
Cancel MISP Syncing JOB

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#6611]
I have a sync job that is running and I want to cancel it.
I tried redis flushdb and tried to disable worker but seems this is a temporary fix only as when the worker are up the job is resuming and continue running again.

How I can stop it completely?

Many thanks with Regards,

**Comment by ahmedxuae91** [comment]
Hi Team, I tried to explore multiple options with no luck. kindly let me know if there is any solution.

**Comment by iglocska** [comment]
flushdb and killing the workers should fix it. Are you sure the job is resuming? Or are you just seeing the current % of completion in the jobs index? Does it actually increase?

**Comment by ahmedxuae91** [comment]
yes i just see the progress is continue to increase and assuming the job is not canceled .. am I wrong?

**Comment by iglocska** [comment]
If it increases it indeed isn't cancelled. That is curious. Clearing redis and killing the process should have killed it, if you do a ps -aux | grep cake-resque do you see anything after killing the workers? Also, are you sure you're flushing the correct redis? MISP is using 3 redis connections altogether, the one you want is the one configured in /var/www/MISP/app/Plugin/CakeResque/Config/config.php

**Comment by Wachizungu** [comment]
Might be slightly off-topic: I just ran into something similar. The jobs and workers were killed, percentage no longer increasing in my case but something in the background was still adding attributes to an event. I was trying to stop the sync of a very large event that was taking hours. The thing that was eating up CPU was ./bin/resque in top output. I ended up restarting the server after killing the jobs, after it was all good.

Anyway:
Did I understand process to kill the sync job correctly?
-> get the correct redis settings (and in particular redis database index, setting redis_database)
sudo cat /var/www/MISP/app/Config/config.php | grep redis
-> kill the workers, all at once via GUI or use MISP/app/Console/cake Admin killWorker [worker_pid]
-> connect to redis and flush the db
redis-cli
SELECT [redis_database]
FLUSHDB

Mainly asking so I can add it to the doc, if you have anything to add (for example an idea about what I mentioned, something still continuing to add attributes to event) that would be great.

**Comment by qbolbk59** [comment]
@Wachizungu Did you already tested these tasks ? 
I am also facing the same issue and i performed all these tasks this morning. But still no luck. I still see all the jobs stuck just like before. And the strange part is that when i check the default worker which is performing the pull job, it says "0 jobs queued".

**Comment by Wachizungu** [comment]
yeah I tested the ones I described but it didn't kill the thing completely, there was still something running somehow. I ended up rebooting the server :/

**Comment by qbolbk59** [comment]
@Wachizungu and reboot helped ?

**Comment by Wachizungu** [comment]
Yes, note that I had cleaned up queues etc with the commands specified before rebooting

**Comment by th3c0rt3x** [comment]
Even reboot didn't help, any other ideas guys?

**Comment by 00willo** [comment]
I also updated the mysql table to clean up the old job.  From the UI, grab the ID of the job.  Then connect the database and execute something like this.

Just make sure you're adjusting the correct job ID. 
```
use misp;

# confirm you have the correct job first
select * from jobs where id = 338;

# now use that id in an update SQL statement
update jobs set status=3,progress=100,message="Killed job manually." where id=338;
```

The UI will then update and show a Failed job, with the message.
