### ISSUE TITLE
The worker was started with a user other than the apache user?!

### ISSUE THREAD

**Issue by georgedumitru** [MISP/MISP#685]
Hello!

I've just deployed MISP and solved most of the critical issues showing up in the admin interface, except the notifications I get in the Workers tab (printscreen below). I use the command below so I don't understand why it tells me the workers were started using another user:

su -s /bin/bash apache -c 'bash /var/www/MISP/app/Console/worker/start.sh'

Any help or suggestion is greatly appreciated!

Thanks,
George

![image](https://cloud.githubusercontent.com/assets/13255884/10393131/de1f65a2-6e95-11e5-88aa-13bf2fc357f4.png)

**Comment by iglocska** [comment]
Hello George,

I checked and I could reproduce the issue under CentOS, and I've pushed a fix for it, so just git pull and it should get fixed.

What caused this was the way that MISP checked whether the process was still alive or not - it simply ran ps -p [pid], which under ubuntu works as expected, but under red hat / centos seems to be blocked. I've changed it to instead look for the pid in /proc/ and tested it with CentOS 6.6. Let me know if it's still not fixed for you!

Best regards,
Andras

**Comment by georgedumitru** [comment]
Hello Andras,

Thanks for the response. I'm a noobie at using git (I just cloned repositories so far) and I'm not quite sure how to use git pull. I went in /var/www/MISP and ran "git pull https://github.com/MISP/MISP.git" so I can get the latest changes but it seems I need to specify a different branch. Can you please guide me on how to do this?

"You asked to pull from the remote 'https://github.com/MISP/MISP.git', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line."

Thank you,
George

**Comment by iglocska** [comment]
Hello George,

If you go to /var/www/MISP then typing

"git pull"

should be enough to get you up to date. If it still complains about not
being on a branch do this:

git checkout master
git pull

Let me know if it doesn't solve it!

Best regards,
Andras

**Comment by georgedumitru** [comment]
Hello again,

The git pull indeed worked as you have told me and MISP is up to date, but the issue remains. The server is deployed on CentOS 6.7 btw.

Thank you,
George

![image](https://cloud.githubusercontent.com/assets/13255884/10425353/a64d8b30-70df-11e5-9112-d9b2540939ec.png)

![image](https://cloud.githubusercontent.com/assets/13255884/10425439/5a301f64-70e0-11e5-8dd5-eff021c6de17.png)

**Comment by iglocska** [comment]
OK, I've managed to reproduce the issue and it looks to be the result of hardening on your system. 

It's down to the open_basedir directive blocking MISP's access to the /proc directory. I will update the diagnostic tool to let the user know that the worker is not necessarily dead, just that MISP doesn't have access to the process information.

For now, just disregard that message, your workers are most likely fine, but I suggest you add /proc to your open_basedir directive if you would like to be able to see the health of the workers. I'll close this ticket once I've pushed the patch.

**Comment by RichieB2B** [comment]
I have the same issue on CentOS 6.7, but we have not set the open_basedir directive. The problem seems to be with get_current_user() which returns the owner of the php script file, not the process owner. You can use posix_getpwuid(posix_geteuid())['name'] but then MISP becomes dependent on the CentOS php-posix package.

**Comment by RichieB2B** [comment]
```
diff --git a/app/Model/Server.php b/app/Model/Server.php
index 3192925..473ee56 100755
--- a/app/Model/Server.php
+++ b/app/Model/Server.php
@@ -1564,7 +1564,7 @@ class Server extends AppModel {
        public function workerDiagnostics(&$workerIssueCount) {
                $this->ResqueStatus = new ResqueStatus\ResqueStatus(Resque::redis());
                $workers = $this->ResqueStatus->getWorkers();
-               $currentUser = get_current_user();
+               $currentUser = posix_getpwuid(posix_geteuid());
                $worker_array = array(
                                'cache' => array('ok' => true),
                                'default' => array('ok' => true),
@@ -1573,7 +1573,7 @@ class Server extends AppModel {
                );
                foreach ($workers as $pid => $worker) {
                        $entry = ($worker['type'] == 'regular') ? $worker['queue'] : $worker['type'];
-                       $correct_user = ($currentUser === $worker['user']);
+                       $correct_user = ($currentUser['name'] === $worker['user']);
                        if (!is_numeric($pid)) throw new MethodNotAllowedException('Non numeric PID found.');
                        $alive = $correct_user ? (file_exists('/proc/' . addslashes($pid))) : false;
                        $ok = true;
```

**Comment by iglocska** [comment]
Great, under ubuntu it returns the process owner, not the owner of the
script file. Argh... :)

**Comment by iglocska** [comment]
Thanks for the heads-up again RichieB2B, I've implemented your suggestion with a small change. If the PHP-posix package is not installed it will simply use whoami. Damn PHP.

**Comment by RichieB2B** [comment]
Thanks. There is another instance of get_current_user() used in the workerRemoveDead() function. Also, you might want to update the INSTALL.centos files to install the php-posix package.

**Comment by iglocska** [comment]
Good catch, will update it later today. As for the php-posix package, this
will work fine without it, it's more of a nice to have with the fallback.

**Comment by georgedumitru** [comment]
Thank you very much for your help in fixing this issue! Works like a charm now! :)

George

**Comment by iglocska** [comment]
Glad it worked out, I've pushed another patch as you will most likely run into issues if you are trying to kill dead workers as RichieB2B pointed out, it now has the same fix applied to it.

Let me know if you run into any issues!
