### ISSUE TITLE
Bug - REST API - Events restSearch ignores page limit

### ISSUE THREAD

**Issue by 01dr1ch** [MISP/MISP#7950]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7.9
| OS version (client)       | RedHat 7.9, Windows 10
| PHP version               | 7.4.24
| MISP version / git hash   | 2.4.150
| Browser                   | Google Chrome Version 95.0.4638.69, Mozilla Firefox 93.0

### Expected behavior
REST API calls to /events/restSearch allow JSON field 'limit' and 'page', both optional, similar to /attributes/restSearch. 'Limit' then configures how many events are returned in the response, while 'page' sets page offset (page: 1 is first set of records/events). User is presented the amount of events requested in 'limit' unless it is last page, where there's less records.

X-Result-Count header then denotes how many records were returned in that particular API REST call.

### Actual behavior
When using /attributes/restSearch, everything works as expected and described in "Expected behavior". When making API call to /events/restSearch, all events are returned at once, regardless of use of 'page' and 'limit' fields in REST JSON request body. Also it is regardless of other optional fields, e.g. org, tags ...

X-Result-Count always returns total count of MISP events present in the MISP instance, instead of those constrained by 'limit' field.

### Steps to reproduce the behavior
Using REST client in MISP instance:

Relative path to query: /events/restSearch

HTTP Headers:
Authorization: <our api key>
Accept: application/json
Content-type: application/json

HTTP body:
{
    "returnFormat": "json",
    "page": "1",
    "limit": "10"
}

### Logs, screenshots, configuration dump, ...
![events-ignoring-page-limit](https://user-images.githubusercontent.com/82970780/141192964-36b42421-8519-463f-afab-1cb975998183.png)

**Comment by righel** [comment]
Hello,
The actual expected behavior is to return the total records matching your filters, so you can properly loop through the paginated response. There `X-Result-Count` was improperly calculated in `/attributes/restSearch` thus returning the current page response size instead of the total matched records, fixed in `develop` by 53ecb2f94660d310d22c0939bc0f63504a5c68d9.

Thanks for reporting.
Let me know if it's clear for you now.

**Comment by 01dr1ch** [comment]
Hello @righel 
OK, understand the issue with X-Result-Count in /attributes/restSearch and now it is clear.

Anyway, the pagination doesn't work in Events no matter what "page" parameter and "limit" parameter I write. Bigger or smaller, I still get on the first call whole set of events - perhaps I didn't make it clear in the original post. Obviously I challenged my testing to be error-less before I posted this. One proof is that I only exchange /attributes/restSearch with /events/restSearch, leaving REST request body the same. Behavior is different.

Thank you.

**Comment by righel** [comment]
I cannot reproduce the bug on my end, please check with the following request:
`POST https://localhost/events/restSearch`
request body:
```json
{
    "returnFormat": "json",
    "page": "1",
    "limit": "1"
}
```

You should get only one event, it might be a big response though, some events have many attributes. If you change the `page` parameter you should get a different event, and so on. A limit of 10 as you show in the screenshot can easily get to a 20mb response size as you are getting.

Alternatively you can reduce the response size by adding the `"metadata": true` property to the request, this will only get the event main properties and exclude the attributes.

Let me know if that helps.

**Comment by 01dr1ch** [comment]
Hi @righel ,

thank you. I have been testing it before only in MISP GUI - REST Client, where the page load was failing (regular Chrome browser) due to lack of memory (my laptop has 16 GB!). It was probably due to lengthy response. Today I tried to process it in linux through JQ library and you're right it is just one event, but with plenty (over 1300) related events (Cryptolaemus correlations of daily IoCs ... meh).

As for the length of response, it was in order of megabytes, which leads me to question why is MISP failing on REST Client page when loading results (I was requesting JSON structure).

Also, as "Export" page is deemed as deprecated and REST client is the recommended way to dump data, it has its resource limits. When one wants to download the data (by clicking Download), I don't see any way how to directly Download them (it has to be loaded first in the page as response) ... which sometimes leads to fail due to memory allocation limits. Perhaps I would consider allowing users to just Download the data without prior loading them as text into the page.

Thank you all in all for clarification. Let me know your thoughts, please - I will appreciate them. Also, I believe this can be closed.

Kind regards,
Oldrich

**Comment by 01dr1ch** [comment]
Fixed in v2.4.151.
