### ISSUE TITLE
Cortex enrichment not allowed

### ISSUE THREAD

**Issue by christiaanvaken** [MISP/MISP#9319]
### Support Questions

When trying to do an enrichment via Cortex I am getting not allowed. The error.log shows this:
```
[MethodNotAllowedException] 0 services are not enabled.
Request URL: /events/queryEnrichment/132250/Enrichment/0/ShadowAttribute/Cortex?_=1696508137154
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}
```
The module is configured correctly so can anybody tell me what's wrong?

### MISP version

v2.4.177

### Operating System

Alma Linux (Docker)

### Operating System version

8

### PHP version

7.4.33

### Browser

Any browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @christiaanvaken ,
Thanks for your report, this indeed was a regression from recent changes in the enrichment mechanism I pushed a fix in the `develop` branch: 3d57ce7aa0b67667aa059775a58f689ca22c3535
It will be included in the next release.

**Comment by christiaanvaken** [comment]
Thanks! Is there a way to fix it myself before the new release is out?

**Comment by righel** [comment]
You can ssh into your MISP instance and do the following:
```bash
wget https://github.com/MISP/MISP/commit/3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
git apply 3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
rm 3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
```

That should apply this patch.

**Comment by christiaanvaken** [comment]
I have applied the patch but it is still not working:

Error: [MethodNotAllowedException] No valid Enrichment options found for this shadowattribute.
Request URL: /events/queryEnrichment/342503/0/Enrichment/ShadowAttribute/Cortex?_=1697046891547

**Comment by christiaanvaken** [comment]
Well I tought it was working but when I applied the patch again, it only shows the normal enrichments and not Cortex.

**Comment by christiaanvaken** [comment]
> You can ssh into your MISP instance and do the following:
> 
> ```shell
> wget https://github.com/MISP/MISP/commit/3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
> git apply 3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
> rm 3d57ce7aa0b67667aa059775a58f689ca22c3535.patch
> ```
> 
> That should apply this patch.

Sorry but it is not working, now it shows the normal enrichments and not Cortex.
