### ISSUE TITLE
Synchronisation issues

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#935]
I'm testing the synchronisation again with two other remote instances, one running 2.4.5 and the other one running the latest commit (2.4.17). I've created an event with distribution "Connected communities" and clicked on publish and it was properly pushed to the instance running 2.4.5 but not to the one running 2.4.17. In my logs I see the following:

$ tail -f resque-worker-error.log resque-2016-02-12.log resque-scheduler-2016-02-05.log error.log debug.log error.log -n 20 | grep '2016-02-12 10'
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 685]
[2016-02-12 10:02:33] main.INFO: got {"queue":"default","id":"7b18a9c56f2ecfaf0c36adb92185c3cf","class":"EventShell","args":[["publish","2133",null,"5522","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"7b18a9c56f2ecfaf0c36adb92185c3cf","class":"EventShell","args":[["publish","2133",null,"5522","1"]]})","worker":"misp.my.org:1593"} []
[2016-02-12 10:02:33] main.INFO: Processing ID:7b18a9c56f2ecfaf0c36adb92185c3cf in default {"type":"process","worker":"misp.my.org:1593","job_id":"7b18a9c56f2ecfaf0c36adb92185c3cf"} []
[2016-02-12 10:02:36] main.INFO: got {"queue":"email","id":"5e4e4327c1978bd9130e042a69022fd1","class":"EventShell","args":[["alertemail","1","5521","2133"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"5e4e4327c1978bd9130e042a69022fd1","class":"EventShell","args":[["alertemail","1","5521","2133"]]})","worker":"misp.my.org:1633"} []
[2016-02-12 10:02:36] main.INFO: Processing ID:5e4e4327c1978bd9130e042a69022fd1 in email {"type":"process","worker":"misp.my.org:1633","job_id":"5e4e4327c1978bd9130e042a69022fd1"} []
[2016-02-12 10:02:36] main.INFO: done ID:7b18a9c56f2ecfaf0c36adb92185c3cf {"type":"done","job_id":"7b18a9c56f2ecfaf0c36adb92185c3cf","time":3119,"worker":"misp.my.org:1593"} []
[2016-02-12 10:02:36] main.INFO: done ID:5e4e4327c1978bd9130e042a69022fd1 {"type":"done","job_id":"5e4e4327c1978bd9130e042a69022fd1","time":129,"worker":"misp.my.org:1633"} []
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 685]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]
2016-02-12 10:02:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 678]

I've also created another event using a sharing group involving the remote instance running 2.4.17 and published it. I see no errors in my logs but I don't see the event on the remote instance either.

$ tail -f resque-worker-error.log resque-2016-02-12.log resque-scheduler-2016-02-05.log error.log debug.log error.log -n 20 | grep '2016-02-12 10:15'
[2016-02-12 10:15:06] main.INFO: got {"queue":"default","id":"3ccde8d1c0c2517d97799f6aa28002c0","class":"EventShell","args":[["publish","2134",null,"5524","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"3ccde8d1c0c2517d97799f6aa28002c0","class":"EventShell","args":[["publish","2134",null,"5524","1"]]})","worker":"misp.my.org:1593"} []
[2016-02-12 10:15:06] main.INFO: got {"queue":"email","id":"8085f0eab777c0810cce62b8c8778284","class":"EventShell","args":[["alertemail","1","5523","2134"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"8085f0eab777c0810cce62b8c8778284","class":"EventShell","args":[["alertemail","1","5523","2134"]]})","worker":"misp.my.org:1633"} []
[2016-02-12 10:15:06] main.INFO: Processing ID:3ccde8d1c0c2517d97799f6aa28002c0 in default {"type":"process","worker":"misp.my.org:1593","job_id":"3ccde8d1c0c2517d97799f6aa28002c0"} []
[2016-02-12 10:15:06] main.INFO: Processing ID:8085f0eab777c0810cce62b8c8778284 in email {"type":"process","worker":"misp.my.org:1633","job_id":"8085f0eab777c0810cce62b8c8778284"} []
[2016-02-12 10:15:06] main.INFO: done ID:8085f0eab777c0810cce62b8c8778284 {"type":"done","job_id":"8085f0eab777c0810cce62b8c8778284","time":132,"worker":"misp.my.org:1633"} []
[2016-02-12 10:15:08] main.INFO: done ID:3ccde8d1c0c2517d97799f6aa28002c0 {"type":"done","job_id":"3ccde8d1c0c2517d97799f6aa28002c0","time":2389,"worker":"misp.my.org:1593"} []

On the side of the instance running 2.4.17, the following can be seen in the logs:

2016-02-12 10:14:43 Error: [MethodNotAllowedException] Invalid Sharing Group or not authorised. (Sync user is not contained in the Sharing group)
Request URL: /events
Stack Trace:
#0 [internal function]: EventsController->add()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

2016-02-12 10:02:10 Notice: Notice (8): Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 1702]
Trace:
Event::__captureObjects() - APP/Model/Event.php, line 1702
Event::_add() - APP/Model/Event.php, line 1807
EventsController::add() - APP/Controller/EventsController.php, line 893
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 185
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 160
[main] - APP/webroot/index.php, line 92

2016-02-12 10:02:10 Notice: Notice (8): Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 1713]
Trace:
Event::__captureObjects() - APP/Model/Event.php, line 1713
Event::_add() - APP/Model/Event.php, line 1807
EventsController::add() - APP/Controller/EventsController.php, line 893
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 185
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 160
[main] - APP/webroot/index.php, line 92

On all instances I'm synchronising with, the organisation name and UUID is the same and match the ones defines on my own instance. Funny enough, those two remote instances are getting events from my instance with distribution "All communities".  My instance is running 2.4.17 with the latest commit (f81960f)

**Comment by Rafiot** [comment]
Do you still have the problem? Did you follow the installation guide here: https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1404.txt ?
And could you try again with the latest version?

**Comment by h122015** [comment]
I did an upgrade today and am using commit bf21195. I created then an event with distribution "Connected Communities" and I see the following in my logs:

==> resque-2016-04-05.log <==
[2016-04-05 13:55:58] main.INFO: got {"queue":"email","id":"67368f792e3c4d5f45d87350e8ada4e2","class":"EventShell","args":[["alertemail","1","7598","2384"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"67368f792e3c4d5f45d87350e8ada4e2","class":"EventShell","args":[["alertemail","1","7598","2384"]]})","worker":"misp.my.org:1633"} []
[2016-04-05 13:55:58] main.INFO: Processing ID:67368f792e3c4d5f45d87350e8ada4e2 in email {"type":"process","worker":"misp.my.org:1633","job_id":"67368f792e3c4d5f45d87350e8ada4e2"} []
[2016-04-05 13:55:58] main.INFO: done ID:67368f792e3c4d5f45d87350e8ada4e2 {"type":"done","job_id":"67368f792e3c4d5f45d87350e8ada4e2","time":148,"worker":"misp.my.org:1633"} []
[2016-04-05 13:55:59] main.INFO: got {"queue":"default","id":"83c0c45e8c92a5d6c5480ce43a0778ad","class":"EventShell","args":[["publish","2384",null,"7599","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"83c0c45e8c92a5d6c5480ce43a0778ad","class":"EventShell","args":[["publish","2384",null,"7599","1"]]})","worker":"misp.my.org:1593"} []
[2016-04-05 13:55:59] main.INFO: Processing ID:83c0c45e8c92a5d6c5480ce43a0778ad in default {"type":"process","worker":"misp.my.org:1593","job_id":"83c0c45e8c92a5d6c5480ce43a0778ad"} []

==> resque-worker-error.log <==
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> resque-worker-error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> resque-worker-error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]

==> resque-worker-error.log <==
2016-04-05 13:55:59 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 699]
Notice Error: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]

==> debug.log <==
2016-04-05 13:55:59 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]

==> resque-worker-error.log <==
2016-04-05 13:55:59 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> error.log <==
2016-04-05 13:56:03 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> resque-worker-error.log <==
2016-04-05 13:56:03 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]
Notice Error: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]

==> debug.log <==
2016-04-05 13:56:03 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]

==> resque-worker-error.log <==
2016-04-05 13:56:03 Notice: Undefined variable: remoteId in [/var/www/MISP/app/Model/Event.php, line 706]

==> resque-2016-04-05.log <==
[2016-04-05 13:56:03] main.INFO: done ID:83c0c45e8c92a5d6c5480ce43a0778ad {"type":"done","job_id":"83c0c45e8c92a5d6c5480ce43a0778ad","time":4503,"worker":"misp.my.org:1593"} []

Right now I'm directly connected to 3 instances (1 running 2.4.31, another one running  2.4.20 and the last one running 2.4.33). The event was pushed through to the instances running 2.4.20 and 2.4.33 but not to the one running 2.4.31.

**Comment by iglocska** [comment]
It seems to be an issue with the error handling. Basically MISP cannot create the event on the remote, receives an error message and tries to parse the error message for event information, which fails. I am working on a fix,l in the meanwhile, could you check if the connection test towards the instance that causes the failure shows that everything's ok?

**Comment by h122015** [comment]
Yep, everything is OK. This is what I get from the connection test:
Local version: 2.4.33
Remote version: 2.4.31
Status: Remote outdated, notify admin!
Compatiblity: Compatible

I am also able to see the events on the remote instance through the Explore tool

**Comment by h122015** [comment]
BTW, this remote instance (2.4.31) is also receiving events from my instance, but only the ones with distribution "All Communities". Any other event with another distribution won't make it.

**Comment by iglocska** [comment]
That is even weirder... I have no idea how it can work for all communities but not for connected communities. Either way, I've pushed a fix that should allow us to debug it a bit easier what's going on.

**Comment by h122015** [comment]
I've applied the patch f4316f6 and tried again with an event with distribution "Connected Communities". The pushing of the events doesn't work anymore with any of the remote instances and I see the following in the logs:

==> resque-2016-04-05.log <==
[2016-04-05 15:52:09] main.INFO: got {"queue":"email","id":"dcd68fc4369881d91bc90ff004e781a9","class":"EventShell","args":[["alertemail","1","7602","2387"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"dcd68fc4369881d91bc90ff004e781a9","class":"EventShell","args":[["alertemail","1","7602","2387"]]})","worker":"misp.my.org:1633"} []
[2016-04-05 15:52:09] main.INFO: Processing ID:dcd68fc4369881d91bc90ff004e781a9 in email {"type":"process","worker":"misp.my.org:1633","job_id":"dcd68fc4369881d91bc90ff004e781a9"} []
[2016-04-05 15:52:09] main.INFO: done ID:dcd68fc4369881d91bc90ff004e781a9 {"type":"done","job_id":"dcd68fc4369881d91bc90ff004e781a9","time":142,"worker":"misp.my.org:1633"} []

==> resque-2016-04-05.log <==
[2016-04-05 15:53:00] main.INFO: done ID:fb7878b574b6ceabb442c4a5ff6fd0c8 {"type":"done","job_id":"fb7878b574b6ceabb442c4a5ff6fd0c8","time":3176165,"worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: got {"queue":"default","id":"9389abf1b23cb8639323d0502b5c04c9","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459847878}]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"9389abf1b23cb8639323d0502b5c04c9","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459847878}]})","worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: Processing ID:9389abf1b23cb8639323d0502b5c04c9 in default {"type":"process","worker":"misp.my.org:1593","job_id":"9389abf1b23cb8639323d0502b5c04c9"} []
[2016-04-05 15:53:00] main.INFO: done ID:9389abf1b23cb8639323d0502b5c04c9 {"type":"done","job_id":"9389abf1b23cb8639323d0502b5c04c9","time":49,"worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: got {"queue":"default","id":"a42d4ca9ffb9be127aaf24abc43f565b","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459850000}]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"a42d4ca9ffb9be127aaf24abc43f565b","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459850000}]})","worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: Processing ID:a42d4ca9ffb9be127aaf24abc43f565b in default {"type":"process","worker":"misp.my.org:1593","job_id":"a42d4ca9ffb9be127aaf24abc43f565b"} []
[2016-04-05 15:53:00] main.INFO: done ID:a42d4ca9ffb9be127aaf24abc43f565b {"type":"done","job_id":"a42d4ca9ffb9be127aaf24abc43f565b","time":48,"worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: got {"queue":"default","id":"4c9c9afbc3830b2979910cc824b68173","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459850007}]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"4c9c9afbc3830b2979910cc824b68173","class":"ServerShell","args":[{"0":"enqueuePull","1":1459861200,"2":"1","3":"2","s_time":1459850007}]})","worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: Processing ID:4c9c9afbc3830b2979910cc824b68173 in default {"type":"process","worker":"misp.my.org:1593","job_id":"4c9c9afbc3830b2979910cc824b68173"} []
[2016-04-05 15:53:00] main.INFO: done ID:4c9c9afbc3830b2979910cc824b68173 {"type":"done","job_id":"4c9c9afbc3830b2979910cc824b68173","time":47,"worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: got {"queue":"default","id":"f58c5e6882b4e5bb468124682c413104","class":"EventShell","args":[["publish","2387",null,"7603","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"f58c5e6882b4e5bb468124682c413104","class":"EventShell","args":[["publish","2387",null,"7603","1"]]})","worker":"misp.my.org:1593"} []
[2016-04-05 15:53:00] main.INFO: Processing ID:f58c5e6882b4e5bb468124682c413104 in default {"type":"process","worker":"misp.my.org:1593","job_id":"f58c5e6882b4e5bb468124682c413104"} []

==> resque-worker-error.log <==
PHP Fatal error:  Call to a member function create() on a non-object in /var/www/MISP/app/Model/Event.php on line 730
Fatal Error Error: Call to a member function create() on a non-object in [/var/www/MISP/app/Model/Event.php, line 730]

==> error.log <==
2016-04-05 15:53:01 Error: Call to a member function create() on a non-object in [/var/www/MISP/app/Model/Event.php, line 730]

==> resque-worker-error.log <==
2016-04-05 15:53:01 Error: Call to a member function create() on a non-object in [/var/www/MISP/app/Model/Event.php, line 730]

**Comment by iglocska** [comment]
My bad that should be fixed now. Could you pull and try again?

**Comment by h122015** [comment]
==> resque-2016-04-05.log <==
[2016-04-05 16:02:44] main.INFO: got {"queue":"email","id":"ff8209bf28bbb29e35e32a6518415e4a","class":"EventShell","args":[["alertemail","1","7605","2388"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"ff8209bf28bbb29e35e32a6518415e4a","class":"EventShell","args":[["alertemail","1","7605","2388"]]})","worker":"misp.my.org:1633"} []
[2016-04-05 16:02:44] main.INFO: Processing ID:ff8209bf28bbb29e35e32a6518415e4a in email {"type":"process","worker":"misp.my.org:1633","job_id":"ff8209bf28bbb29e35e32a6518415e4a"} []
[2016-04-05 16:02:44] main.INFO: done ID:ff8209bf28bbb29e35e32a6518415e4a {"type":"done","job_id":"ff8209bf28bbb29e35e32a6518415e4a","time":124,"worker":"misp.my.org:1633"} []
[2016-04-05 16:02:46] main.INFO: got {"queue":"default","id":"754123fc2457bf9303c4c24c473c1402","class":"EventShell","args":[["publish","2388",null,"7606","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"754123fc2457bf9303c4c24c473c1402","class":"EventShell","args":[["publish","2388",null,"7606","1"]]})","worker":"misp.my.org:1593"} []
[2016-04-05 16:02:46] main.INFO: Processing ID:754123fc2457bf9303c4c24c473c1402 in default {"type":"process","worker":"misp.my.org:1593","job_id":"754123fc2457bf9303c4c24c473c1402"} []

==> resque-worker-error.log <==
Notice Error: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> debug.log <==
2016-04-05 16:02:47 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> resque-worker-error.log <==
2016-04-05 16:02:47 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]
Notice Error: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> debug.log <==
2016-04-05 16:02:48 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> resque-worker-error.log <==
2016-04-05 16:02:48 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> error.log <==
2016-04-05 16:02:50 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> resque-worker-error.log <==
2016-04-05 16:02:50 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]
Notice Error: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> debug.log <==
2016-04-05 16:02:50 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> resque-worker-error.log <==
2016-04-05 16:02:50 Notice: Undefined variable: nrewTextBody in [/var/www/MISP/app/Model/Event.php, line 739]

==> resque-2016-04-05.log <==
[2016-04-05 16:02:50] main.INFO: done ID:754123fc2457bf9303c4c24c473c1402 {"type":"done","job_id":"754123fc2457bf9303c4c24c473c1402","time":4274,"worker":"misp.my.org:1593"} []

**Comment by iglocska** [comment]
OK that was a fat finger issue on my end, pushed a fix for the typo.

**Comment by h122015** [comment]
==> resque-2016-04-05.log <==
[2016-04-05 16:09:29] main.INFO: got {"queue":"email","id":"0640a8cc1cf743a5ed13d631199b1840","class":"EventShell","args":[["alertemail","1","7607","2389"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"0640a8cc1cf743a5ed13d631199b1840","class":"EventShell","args":[["alertemail","1","7607","2389"]]})","worker":"misp.my.org:1633"} []
[2016-04-05 16:09:29] main.INFO: Processing ID:0640a8cc1cf743a5ed13d631199b1840 in email {"type":"process","worker":"misp.my.org:1633","job_id":"0640a8cc1cf743a5ed13d631199b1840"} []
[2016-04-05 16:09:29] main.INFO: done ID:0640a8cc1cf743a5ed13d631199b1840 {"type":"done","job_id":"0640a8cc1cf743a5ed13d631199b1840","time":126,"worker":"misp.my.org:1633"} []
[2016-04-05 16:09:30] main.INFO: got {"queue":"default","id":"02d9b44e20405439f3ec48f2b119464b","class":"EventShell","args":[["publish","2389",null,"7608","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"02d9b44e20405439f3ec48f2b119464b","class":"EventShell","args":[["publish","2389",null,"7608","1"]]})","worker":"misp.my.org:1593"} []
[2016-04-05 16:09:30] main.INFO: Processing ID:02d9b44e20405439f3ec48f2b119464b in default {"type":"process","worker":"misp.my.org:1593","job_id":"02d9b44e20405439f3ec48f2b119464b"} []

==> resque-worker-error.log <==
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> error.log <==
2016-04-05 16:09:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> resque-worker-error.log <==
2016-04-05 16:09:33 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 698]

==> resque-2016-04-05.log <==
[2016-04-05 16:09:33] main.INFO: done ID:02d9b44e20405439f3ec48f2b119464b {"type":"done","job_id":"02d9b44e20405439f3ec48f2b119464b","time":3212,"worker":"misp.my.org:1593"} []

**Comment by iglocska** [comment]
Interesting, now we're getting closer to the interesting things. Let's try something new.

**Comment by iglocska** [comment]
Could you try again now?

**Comment by h122015** [comment]
==> resque-2016-04-05.log <==
[2016-04-05 16:13:54] main.INFO: got {"queue":"email","id":"b60b4e252f77e24f726ba706de09af41","class":"EventShell","args":[["alertemail","1","7609","2390"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"email","id":"b60b4e252f77e24f726ba706de09af41","class":"EventShell","args":[["alertemail","1","7609","2390"]]})","worker":"misp.my.org:1633"} []
[2016-04-05 16:13:54] main.INFO: Processing ID:b60b4e252f77e24f726ba706de09af41 in email {"type":"process","worker":"misp.my.org:1633","job_id":"b60b4e252f77e24f726ba706de09af41"} []
[2016-04-05 16:13:55] main.INFO: done ID:b60b4e252f77e24f726ba706de09af41 {"type":"done","job_id":"b60b4e252f77e24f726ba706de09af41","time":142,"worker":"misp.my.org:1633"} []
[2016-04-05 16:13:58] main.INFO: got {"queue":"default","id":"99f6c3d3d4517312810b650c8330812f","class":"EventShell","args":[["publish","2390",null,"7610","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"99f6c3d3d4517312810b650c8330812f","class":"EventShell","args":[["publish","2390",null,"7610","1"]]})","worker":"misp.my.org:1593"} []
[2016-04-05 16:13:58] main.INFO: Processing ID:99f6c3d3d4517312810b650c8330812f in default {"type":"process","worker":"misp.my.org:1593","job_id":"99f6c3d3d4517312810b650c8330812f"} []
[2016-04-05 16:14:02] main.INFO: done ID:99f6c3d3d4517312810b650c8330812f {"type":"done","job_id":"99f6c3d3d4517312810b650c8330812f","time":3482,"worker":"misp.my.org:1593"} []

Still no event created on the remote instance using 2.4.31.

**Comment by iglocska** [comment]
Could you check your audit logs? It should show the error message returned from the 2.4.31 instance.

**Comment by iglocska** [comment]
Sorry for making this process this "interactive", in order to reproduce the issue I need to know what the remote instance is reporting back as the reason for the failure - the idea now is to catch and log that message which we hopefully just achieved :)

**Comment by h122015** [comment]
Where do I find the audit logs?

**Comment by iglocska** [comment]
Ah, my bad, it's in the application via the web interface. Just go to Audit -> List logs, what you are looking for are entries with the "action" column being "warning".

**Comment by h122015** [comment]
641263          SYSTEM      SYSTEM          Server      5   warning     Uploading Event (2390) to Server (5)    Returned message:  
641262          SYSTEM      SYSTEM      2016-04-05 16:14:01     Server      5   warning     Warning: Sync to Server ('5') initiated, but the remote instance is a few hotfixes behind.  
641261          SYSTEM      SYSTEM          Server      4   warning     Uploading Event (2390) to Server (4)    Returned message:  
641260          SYSTEM      SYSTEM          Server      3   warning     Uploading Event (2390) to Server (3)    Returned message:  
641259          SYSTEM      SYSTEM      2016-04-05 16:13:59     Server      3   warning     Warning: Sync to Server ('3') initiated, but the remote instance is a few hotfixes behind.  
641258      127.0.0.1   mail@my.org     MyOrg   2016-04-05 16:13:47     Event   2390    add     Event (2390): Test event. Please dismiss    distribution () => (2), proposal_email_lock () => (0), locked () => (0), org_id () => (1), orgc_id () => (1), date () => (2016-04-05), threat_level_id () => (4), analysis () => (2), info () => (Test event. Please dismiss), user_id () => (1), uuid () => (5703c81b-aed8-4994-b119-36c8ac100567) 
641257      127.0.0.1   mail@my.org     MyOrg   2016-04-05 16:13:03     Event   2389    delete      Event (2389): Test event. Please dismiss  
641256      127.0.0.1   mail@my.org     MyOrg   2016-04-05 16:13:03     EventBlacklist      86      add     EventBlacklist (86)     event_uuid () => (5703c70f-22c8-4bff-9eef-36c9ac100567), event_info () => (Test event. Please dismiss), event_orgc () => (MyOrg), created () => (2016-04-05 16:13:03)

**Comment by h122015** [comment]
Server 3 is the one running 2.4.31
Server 4 is running 2.4.33
Server 5 is running 2.4.20

**Comment by iglocska** [comment]
Pushed another change, let's see if we get some better feedback.

**Comment by iglocska** [comment]
Added more logging to it.

**Comment by h122015** [comment]
641273          mail@my.org     MyOrg   2016-04-05 17:00:28     Event (2391): publis    0   publish  
641272          SYSTEM      SYSTEM          Server      5   warning     Uploading Event (2391) to Server (5)    Returned message:  
641271          SYSTEM      SYSTEM      2016-04-05 17:00:26     Server      5   warning     Warning: Sync to Server ('5') initiated, but the remote instance is a few hotfixes behind.  
641270          SYSTEM      SYSTEM          Server      4   warning     Uploading Event (2391) to Server (4)    Returned message:  
641269          SYSTEM      SYSTEM          Server      3   warning     Uploading Event (2391) to Server (3)    Returned message:  
641268          SYSTEM      SYSTEM      2016-04-05 17:00:23     Server      3   warning     Warning: Sync to Server ('3') initiated, but the remote instance is a few hotfixes behind.  
641267      127.0.0.2   mail@my.org     MyOrg   2016-04-05 17:00:09     Event   2391    add     Event (2391): Test event. Please dismiss    distribution () => (2), proposal_email_lock () => (0), locked () => (0), org_id () => (1), orgc_id () => (1), date () => (2016-04-05), threat_level_id () => (4), analysis () => (2), info () => (Test event. Please dismiss), user_id () => (1), uuid () => (5703d2f9-f910-451a-893c-36cdac100567) 
641266      127.0.0.2   mail@my.org     MyOrg   2016-04-05 16:59:38     Event   2390    delete      Event (2390): Test event. Please dismiss  
641265      127.0.0.2   mail@my.org     MyOrg   2016-04-05 16:59:38     EventBlacklist      87      add     EventBlacklist (87)     event_uuid () => (5703c81b-aed8-4994-b119-36c8ac100567), event_info () => (Test event

**Comment by iglocska** [comment]
Let's try again... Sorry for all the trial and error.

**Comment by h122015** [comment]
641283          mail@my.org     MyOrg   2016-04-05 17:16:57     Event (2392): publis    0   publish  
641282          SYSTEM      SYSTEM          Server      5   warning     Uploading Event (2392) to Server (5)    Returned message:  
641281          SYSTEM      SYSTEM      2016-04-05 17:16:56     Server      5   warning     Warning: Sync to Server ('5') initiated, but the remote instance is a few hotfixes behind.  
641280          SYSTEM      SYSTEM          Server      4   warning     Uploading Event (2392) to Server (4)    Returned message:  
641279          SYSTEM      SYSTEM          Server      3   warning     Uploading Event (2392) to Server (3)    Returned message:  
641278          SYSTEM      SYSTEM      2016-04-05 17:16:54     Server      3   warning     Warning: Sync to Server ('3') initiated, but the remote instance is a few hotfixes behind.  
641277      127.0.0.2   mail@my.org     MyOrg   2016-04-05 17:16:43     Event   2392    add     Event (2392): Test event. Please dismiss    distribution () => (2), proposal_email_lock () => (0), locked () => (0), org_id () => (1), orgc_id () => (1), date () => (2016-04-05), threat_level_id () => (4), analysis () => (2), info () => (Test event. Please dismiss), user_id () => (1), uuid () => (5703d6db-106c-43a3-8804-3837ac100567) 
641276      127.0.0.2   mail@my.org     MyOrg   2016-04-05 17:16:26     Event   2391    delete      Event (2391): Test event. Please dismiss  
641275      127.0.0.2   mail@my.org     MyOrg   2016-04-05 17:16:26     EventBlacklist      88      add     EventBlacklist (88)     event_uuid () => (5703d2f9-f910-451a-893c-36cdac100567), event_info () => (Test event. Please dismiss), event_orgc () => (MyOrg), created () => (2016-04-05 17:16:26)

**Comment by iglocska** [comment]
Bloody hell. OK, I'll try to reproduce the issue on my end somehow so I can catch the error.

**Comment by h122015** [comment]
While we are at it, I've also noticed that the synchronisation using distribution "Sharing Group" doesn't consistently work with all the remote instances. From the three remote instances I have configured, only the one running 2.4.33 (CIRCL) displays the events I push using the sharing groups. On the remaining two remote instances I don't see the events pushed nor errors in the logs.

**Comment by iglocska** [comment]
Alright, I'll go afk for a few hours to clear my head and I'll try to debug it all tonight, I'll let you know here once I found out what's going on!

**Comment by iglocska** [comment]
I've pushed some changes earlier today, could you give it another shot when you have some time? Especially interested in the audit logs.

**Comment by h122015** [comment]
666467          mail@my.org     MyOrg   2016-04-07 08:47:27     Event (2399): publis    0   publish  
666466          SYSTEM      SYSTEM      0000-00-00 00:00:00     Server      5   warning     Uploading Event (2399) to Server (5)    Returned message:  
666465          SYSTEM      SYSTEM      0000-00-00 00:00:00     Server      3   warning     Uploading Event (2399) to Server (3)    Returned message:  
666464          SYSTEM      SYSTEM      2016-04-07 08:47:23     Server      3   warning     Warning: Sync to Server ('3') initiated, but the remote instance is a few hotfixes behind.  
666463      127.0.0.1   mail@my.org     MyOrg   2016-04-07 08:47:06     Event   2399    add     Event (2399): Test event. Please dismiss    distribution () => (2), proposal_email_lock () => (0), locked () => (0), org_id () => (1), orgc_id () => (1), date () => (2016-04-07), threat_level_id () => (4), analysis () => (2), info () => (Test event. Please dismiss), user_id () => (5), uuid () => (5706026a-4a98-4103-bedd-41c5ac100567) 

There is no mention to server 4 here, even though server 4 received my event

**Comment by iglocska** [comment]
That is interesting. Time to dig deeper then, generally you should not get any of those warnings at all.

**Comment by iglocska** [comment]
OK, think I found it. 

The issue was that the remote you were pushing to didn't have the baseurl set - in general this should be fine, but due to a bug, when an event was getting edited it sent a redirect to a relative path, which failed when your MISP tried to use it without the baseurl. 

Pushed a fix that pre-pends the baseurl as known to your MISP from the server object.

Let me know if it works and thanks for bearing with me on this!

**Comment by h122015** [comment]
No, I'm still not seeing the event on the remote instance running 2.4.31

**Comment by h122015** [comment]
Now that you mention that with the baseurl. On my instance I have the BaseURL so defined:

https://inf-exchange.organisation.be

This resolves to a valid IP address and also the certificate was issued to that URL.

If I login to the remote instance, I see that all links point to https://inf-exchange.bd. inf-exchange.bd doesn't resolve to a valid IP address

**Comment by iglocska** [comment]
Argh. Does fixing the baseurl setting resolve it?

**Comment by h122015** [comment]
If I change the BaseURL on my instance to https://inf-exchange.bd I'm not even able to see the events on the remote instance since it won't resolve to a valid IP address. Is there a way to define an alternative BaseURL, so if in case with the first one doesn't work, try the second?

**Comment by h122015** [comment]
I could also contact the admin of the remote instance and ask him if he can change something so the links on that instance all point to inf-exchange.organisation.be

**Comment by h122015** [comment]
But then why is it working for the events with distribution "All communities" and not for "Connected communities"?

**Comment by iglocska** [comment]
No idea. That is indeed really odd, I don't seem to be able to reproduce it
in any way.

**Comment by iglocska** [comment]
Oh actually. Unless they get your all community events via a 3rd party!

**Comment by h122015** [comment]
I think they are receiving them directly from my instance. They have enabled the extended display and under the column "Member Org" I see my organisation's name

**Comment by iglocska** [comment]
Ah indeed, that should give it away. This is incredibly odd.

**Comment by adulau** [comment]
We will close this issue. If this is no fixed, feel free to reopen the issue.
